---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - growthbook.infra.doodle.com
  resources:
  - growthbookclients
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - growthbook.infra.doodle.com
  resources:
  - growthbookclients/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - growthbook.infra.doodle.com
  resources:
  - growthbookfeatures
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - growthbook.infra.doodle.com
  resources:
  - growthbookfeatures/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - growthbook.infra.doodle.com
  resources:
  - growthbookinstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - growthbook.infra.doodle.com
  resources:
  - growthbookinstances/status
  verbs:
  - get
  - patch
  - update
