{{- if .Values.clusterRBAC.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "k8sgrowthbook-controller.fullname" . }}-view
  labels:
    app.kubernetes.io/name: {{ include "k8sgrowthbook-controller.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "k8sgrowthbook-controller.chart" . }}
    rbac.authorization.k8s.io/aggregate-to-view: "true"
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}
rules:
- apiGroups:
  - growthbook.infra.doodle.com
  resources:
  - growthbookclients
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - growthbook.infra.doodle.com
  resources:
  - growthbookfeatures
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - growthbook.infra.doodle.com
  resources:
  - growthbookinstances
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - growthbook.infra.doodle.com
  resources:
  - growthbookinstances/status
  verbs:
  - get
- apiGroups:
  - growthbook.infra.doodle.com
  resources:
  - growthbookorganizations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - growthbook.infra.doodle.com
  resources:
  - growthbookusers
  verbs:
  - get
  - list
  - watch
{{- end }}
