{{- if .Values.clusterRBAC.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "growthbook-controller.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "growthbook-controller.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "growthbook-controller.chart" . }}
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - growthbook.infra.doodle.com
  resources:
  - growthbookclients
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - growthbook.infra.doodle.com
  resources:
  - growthbookfeatures
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - growthbook.infra.doodle.com
  resources:
  - growthbookinstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - growthbook.infra.doodle.com
  resources:
  - growthbookinstances/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - growthbook.infra.doodle.com
  resources:
  - growthbookorganizations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - growthbook.infra.doodle.com
  resources:
  - growthbookusers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
{{- end }}
