apiVersion: v2
appVersion: v0.0.2
description: HTTP request duplicator
home: https://github.com/DoodleScheduling/k8sgrowthbook-controller
maintainers:
- name: devops
  email: devops@doodle.com
keywords:
- kubernetes-controller
- http-proxy
- webhook-duplicator
- duplicate-http-requests
- request-clone
name: k8sgrowthbook-controller
sources:
- https://github.com/DoodleScheduling/k8sgrowthbook-controller
version: 0.0.2
