apiVersion: v2
appVersion: v0.0.0
description: Kubernetes controller for managing growthbook
home: https://github.com/DoodleScheduling/growthbook-controller
maintainers:
- name: devops
  email: devops@doodle.com
keywords:
- kubernetes-controller
- growthbook
- features
- clients
- sdk
- organizations
name: growthbook-controller
sources:
- https://github.com/DoodleScheduling/growthbook-controller
version: 0.0.0
