apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: growthbook-controller-
resources:
- role.yaml
- role_binding.yaml
- leader_election_role.yaml
- leader_election_role_binding.yaml
- growthbook_editor_role.yaml
- growthbook_viewer_role.yaml
