apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: growthbookfeatures-editor-role
rules:
- apiGroups:
  - growthbook.infra.doodle.com
  resources:
  - growthbookfeatures
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - growthbook.infra.doodle.com
  resources:
  - growthbookfeatures/status
  verbs:
  - get
