---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - growthbook.infra.doodle.com
  resources:
  - growthbookclients
  - growthbookfeatures
  - growthbookinstances
  - growthbookorganizations
  - growthbookusers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - growthbook.infra.doodle.com
  resources:
  - growthbookinstances/status
  verbs:
  - get
  - patch
  - update
